spring.application.name=HSFProject
server.port=8080
server.servlet.context-path=/HSFProject

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSFProject;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

payos.clientId=d89af32a-10c8-4f6e-be96-fa7b5286b587
payos.apiKey=c8287ccc-bedb-4757-8284-3e5b2876c6f4
payos.checksumKey=809a12f114478ee4ffe2bdb19a0049d9f434f4ea3bf81e6c2a9ffe0b64b50d61

# MAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=longnguyen01042004@gmail.com
spring.mail.password=bwojekuzreptflyv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.post-dir=uploads/posts