spring.application.name=HSFProject
server.port=8080
server.servlet.context-path=/HSFProject

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSFProject;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

payos.clientId=d89af32a-10c8-4f6e-be96-fa7b5286b587
payos.apiKey=c8287ccc-bedb-4757-8284-3e5b2876c6f4
payos.checksumKey=809a12f114478ee4ffe2bdb19a0049d9f434f4ea3bf81e6c2a9ffe0b64b50d61